name: src_lint
description: A custom lint that prevents imports from unrelated src directories.
version: 1.0.0
homepage: https://github.com/s0nerik/src_lint/tree/main/src_lint
repository: https://github.com/s0nerik/src_lint/tree/main/src_lint
topics:
  - lint
  - structure
  - protected
  - visibility

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^7.4.5
  custom_lint_builder: ^0.7.5
  path: ^1.9.1
